[tool.poetry]
name = "thrift-pyi"
version = "0.1.0"
description = "This is simple `.pyi` stubs generator from thrift interfaces"
authors = ["Aleksei Maslakov <lesha.maslakov@gmail.com>"]
license = "MIT"
packages = [
    { include = "thriftpyi", from = "src" },
]

[tool.poetry.scripts]
thriftpyi = "thriftpyi.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
