[tool.poetry]
name = "thrift-pyi"
version = "0.1.0-alpha.1"
description = "This is simple `.pyi` stubs generator from thrift interfaces"
authors = ["Aleksei Maslakov <lesha.maslakov@gmail.com>"]
license = "MIT"
packages = [
    { include = "thriftpyi", from = "src" },
]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true

[tool.poetry.scripts]
thriftpyi = "thriftpyi.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
jinja2 = "^2.10"
black = "=19.3b0"
thriftpy2 = "^0.4.2"
autoflake = "^1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
